version: "3"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/blogify_db
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: node app.js

volumes:
  mongo_data:

